//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_qebula_yazılma.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QachqinKomEntities : DbContext
    {
        public QachqinKomEntities()
            : base("name=QachqinKomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Istifadechiler> Istifadechilers { get; set; }
        public virtual DbSet<Istiqamet> Istiqamets { get; set; }
        public virtual DbSet<Kateqoriya> Kateqoriyas { get; set; }
        public virtual DbSet<Kochkun_dushduyu_rayon> Kochkun_dushduyu_rayon { get; set; }
        public virtual DbSet<Meskunlashdigi_rayon> Meskunlashdigi_rayon { get; set; }
        public virtual DbSet<Qebul> Qebuls { get; set; }
        public virtual DbSet<Sosial_durum> Sosial_durum { get; set; }
    }
}
