//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_qebula_yazılma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istifadechiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Istifadechiler()
        {
            this.Qebuls = new HashSet<Qebul>();
            this.Qebuls1 = new HashSet<Qebul>();
        }
    
        public int istifadechi_id { get; set; }
        public string istifadechi_adi { get; set; }
        public Nullable<bool> istifadechi_novu { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string shifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qebul> Qebuls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qebul> Qebuls1 { get; set; }
    }
}
