//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_qebula_yazılma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qebul
    {
        public int qebul_id { get; set; }
        public int istifadechi_id { get; set; }
        public string ad_soyad { get; set; }
        public System.DateTime dogum_tarixi { get; set; }
        public int sh_vesiqesi_no { get; set; }
        public string fin { get; set; }
        public string email { get; set; }
        public int mobile { get; set; }
        public int phone { get; set; }
        public int kochkun_rayon_id { get; set; }
        public int meskunlashdigi_rayon_id { get; set; }
        public string unvan { get; set; }
        public int durum_id { get; set; }
        public int kateqoriya_id { get; set; }
        public int istiqamet_id { get; set; }
        public int qebul_eden_id { get; set; }
        public System.DateTime qebul_date { get; set; }
        public string qeyd { get; set; }
    
        public virtual Istifadechiler Istifadechiler { get; set; }
        public virtual Istifadechiler Istifadechiler1 { get; set; }
        public virtual Istiqamet Istiqamet { get; set; }
        public virtual Kateqoriya Kateqoriya { get; set; }
        public virtual Kochkun_dushduyu_rayon Kochkun_dushduyu_rayon { get; set; }
        public virtual Meskunlashdigi_rayon Meskunlashdigi_rayon { get; set; }
        public virtual Sosial_durum Sosial_durum { get; set; }
    }
}
